services:
  auto-claimer:
    image: flare-autoclaimer
    env_file: .env
    command: yarn auto-claimer
    restart: unless-stopped

  cli:
    image: flare-autoclaimer
    env_file: .env
    entrypoint: ["yarn", "cli"]
